name: flutter_esim_pro
description: "A Flutter plugin to check eSIM compatibility and install eSIM profiles, enabling seamless integration of eSIM functionality within Flutter apps."
version: 0.0.2
homepage: https://github.com/chothanijaydip/flutter_esim_pro.git
repository: https://github.com/chothanijaydip/flutter_esim_pro
issue_tracker: https://github.com/chothanijaydip/flutter_esim_pro/issues

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
 
  plugin:
    platforms:
      android:
        package: com.sentientcode.flutter_esim_pro
        pluginClass: FlutterEsimProPlugin
      ios:
        pluginClass: FlutterEsimProPlugin
